#!/bin/bash

set -e

script/vendor-datomic-free
pushd `ls -d -1 vendor/datomic/* | tail -n 1` > /dev/null

echo "Starting local Datomic REST client"
bin/rest -p 9000 free datomic:mem:// 2>&1 &
child_pid=$!

popd

echo "Waiting for Datomic REST client to come up on port 9000"
max_wait=60 #  seconds to wait for bin/rest to come up
while [ $max_wait -gt 0 ] && [ -z "`lsof -i :9000`" ]; do
  max_wait=$((max_wait-1))
  sleep 1
done

echo "Running specs..."
INTEGRATION=true bundle exec rake spec

# Clean up child processes
for pid in `ps -ef | awk '$3 == '$child_pid' { print $2 }'`;  do
  kill $pid
done
kill $child_pid
